package produk;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.SwingUtilities;
import javax.swing.Timer;
import koneksi.koneksi;
import mainOwner.MainOwner;
import notifikasi.notifGagal;
import notifikasi.notifSukses;
import raven.glasspanepopup.GlassPanePopup;

/**
 *
 * @author YAVIE
 */
public class form_pproduk extends javax.swing.JPanel {
    Color DefaultColor,ClickedColor;
    private String t;
   private panelProduk_O panelProduk_O;
    public form_pproduk() {
        initComponents();
        idpro.setVisible(false);
                
        
//         idpro.setVisible(false);
     
      /*  DefaultColor=new Color(128,147,131);
        ClickedColor=new Color(174,197,182);
        skembali.setBackground(DefaultColor); */
        jams.setForeground(new Color (0,0,0));
        haris.setForeground(new Color (0,0,0));
                }
        public void setPanelProduk_O(panelProduk_O panelProduk_O) {
        this.panelProduk_O = panelProduk_O;
    }

 
    /**
     * 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jen = new combo_suggestion.ComboBoxSuggestion();
        jLabel11 = new javax.swing.JLabel();
        skembali = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        simpans = new javax.swing.JButton();
        idpro = new javax.swing.JTextField();
        jams = new javax.swing.JTextField();
        haris = new javax.swing.JTextField();
        nam = new javax.swing.JTextField();
        har = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();
        panelCustom1 = new panelcustom.panelCustom();

        setBackground(new java.awt.Color(237, 237, 237));
        setPreferredSize(new java.awt.Dimension(1052, 689));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jen.setBorder(null);
        jen.setEditable(false);
        jen.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "kiloan", "satuan" }));
        jen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenActionPerformed(evt);
            }
        });
        add(jen, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 240, 140, 20));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/produk/Frame 2 (1).png"))); // NOI18N
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 230, -1, 40));

        skembali.setBackground(new java.awt.Color(128, 147, 131));
        skembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                skembaliMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/produk/Desain tanpa judul (38).png"))); // NOI18N
        skembali.add(jLabel1);

        add(skembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 530, 50, 50));

        simpans.setBackground(new java.awt.Color(10, 172, 42));
        simpans.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        simpans.setForeground(new java.awt.Color(255, 255, 255));
        simpans.setText("Simpan");
        simpans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpansActionPerformed(evt);
            }
        });
        add(simpans, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 460, 90, 30));

        idpro.setEditable(false);
        idpro.setText("id");
        add(idpro, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 70, 210, -1));

        jams.setBorder(null);
        jams.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jamsFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jamsFocusLost(evt);
            }
        });
        jams.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jamsActionPerformed(evt);
            }
        });
        add(jams, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 400, 80, 20));

        haris.setBorder(null);
        haris.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                harisFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                harisFocusLost(evt);
            }
        });
        haris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                harisActionPerformed(evt);
            }
        });
        add(haris, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 400, 80, 20));

        nam.setBorder(null);
        nam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namActionPerformed(evt);
            }
        });
        add(nam, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, 270, 20));

        har.setBorder(null);
        har.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                harActionPerformed(evt);
            }
        });
        add(har, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 320, 270, 20));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/produk/Frame 2.png"))); // NOI18N
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 390, -1, 40));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/produk/Frame 2.png"))); // NOI18N
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 390, -1, 40));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/produk/Frame 1.png"))); // NOI18N
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 310, -1, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/produk/Frame 1.png"))); // NOI18N
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, 330, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Batas Waktu");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 360, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Nama Produk");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Jenis Produk");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 190, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Harga Produk");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 280, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Perbarui Data");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 210, 50));

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/produk/KK (17).png"))); // NOI18N
        add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 630));
        add(panelCustom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void harisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_harisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_harisActionPerformed

    private void harActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_harActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_harActionPerformed

    private void jamsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jamsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jamsActionPerformed

    private void simpansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpansActionPerformed
   
    String id = idpro.getText();
    String nama = nam.getText();
    String harga = har.getText();
    String jenis = (String) jen.getSelectedItem();
    String hari = haris.getText().trim();
    String jam = jams.getText().trim();
        if (harga.isEmpty()) {
           GlassPanePopup.showPopup(new notifGagal("Harga produk tidak boleh kosong"));
            return;
        }

        if (nama.isEmpty()) {
           GlassPanePopup.showPopup(new notifGagal("Nama produk Tidak boleh kosong"));
            return;
        }

 try {
    // Ensure that the value of "jam" is within the range of 0-24
    int jamValue = Integer.parseInt(jam);
    if (jamValue < 0 || jamValue > 24) {
     GlassPanePopup.showPopup(new notifGagal("Jam harus berada dalam rentang 0 - 24 "));
        return;
    }
} catch (NumberFormatException e) {
    GlassPanePopup.showPopup(new notifGagal("Jam harus berupa angka"));
    return;
}
        try { 
    // Ensure that the value of "jam" is within the range of 0-24
        int hariValue = Integer.parseInt(hari);
        if (hariValue < 0 || hariValue > 356) {
       GlassPanePopup.showPopup(new notifGagal("Hari harus berada dalam rentang 0 - 365"));
        return;
    }
} catch (NumberFormatException e) {
    // Display the appropriate message and close button
    GlassPanePopup.showPopup(new notifGagal("Hari harus berupa angka"));
    return;
}
    try {
        Connection conn = koneksi.configDB();

        String sql = "UPDATE produk SET nama_produk = ?, harga_produk = ?, jenis_produk = ?, hari = ?, jam = ? WHERE id_produk=?";
        PreparedStatement p = conn.prepareStatement(sql);
        p.setString(1, nama);
        p.setString(2, harga);
        p.setString(3, jenis);
        p.setString(4, hari);
        p.setString(5, jam);
        p.setString(6, id);
        int updatedRows = p.executeUpdate();
        
     
        if (updatedRows > 0) {
         GlassPanePopup.showPopup(new notifSukses("Data berhasil diperbarui"));
            int durationInMillis = 2000;
            Timer timer = new Timer(durationInMillis, new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    GlassPanePopup.closePopupAll(); 
                }
            });
            timer.setRepeats(false);
            timer.start();

        } else {
            GlassPanePopup.showPopup(new notifGagal("Data tidak ditemukan "));
              int durationInMillis = 2000;
            Timer timer = new Timer(durationInMillis, new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    GlassPanePopup.closePopupAll(); 
                }
            });
            timer.setRepeats(false);
            timer.start();
        }
        nam.setText("");
        har.setText("");
    } catch (SQLException e) {
        System.out.println("Update Error: " + e.getMessage());
    }
    }//GEN-LAST:event_simpansActionPerformed

    private void skembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_skembaliMouseClicked

    MainOwner mainInstance = (MainOwner) SwingUtilities.getWindowAncestor(this);
    mainInstance.showFormOwner(new produk.panelProduk_O(mainInstance));

    }//GEN-LAST:event_skembaliMouseClicked

    private void harisFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_harisFocusGained
        // TODO add your handling code here:
        if(haris.getText().equals(" Hari...")) {
            haris.setText("");
            haris.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_harisFocusGained

    private void harisFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_harisFocusLost
               if(haris.getText().equals("")) {
            haris.setText(" Hari...");
            haris.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_harisFocusLost

    private void jamsFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jamsFocusGained
        // TODO add your handling code here:
                        if(jams.getText().equals(" Jam...")) {
            jams.setText("");
            jams.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_jamsFocusGained

    private void jamsFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jamsFocusLost
               if(jams.getText().equals("")) {
            jams.setText(" Jam...");
            jams.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_jamsFocusLost

    private void jenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jenActionPerformed

    private void namActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    public static javax.swing.JTextField har;
    public static javax.swing.JTextField haris;
    public static javax.swing.JTextField idpro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JTextField jams;
    public static combo_suggestion.ComboBoxSuggestion jen;
    public static javax.swing.JTextField nam;
    private panelcustom.panelCustom panelCustom1;
    private javax.swing.JButton simpans;
    private javax.swing.JPanel skembali;
    // End of variables declaration//GEN-END:variables
}
