/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frame;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
import mainOwner.MainOwner;

/**
 *
 * @author YAVIE
 */
public class form_pproduk extends javax.swing.JPanel {
    Color DefaultColor,ClickedColor;
    private String t;
        private panelProduk_O panelProduk_O;
    public form_pproduk() {
        initComponents();
        berhasils.setVisible(false);
        jamrentang.setVisible(false);
        jamangka.setVisible(false);
        harirentang.setVisible(false);
        hariangka.setVisible(false);
        datatak.setVisible(false);
        harko.setVisible(false);
        namproko.setVisible(false);
            close.setVisible(false);
      /*  DefaultColor=new Color(128,147,131);
        ClickedColor=new Color(174,197,182);
        skembali.setBackground(DefaultColor); */
        jams.setForeground(new Color (0,0,0));
        haris.setForeground(new Color (0,0,0));
                }
        public void setPanelProduk_O(panelProduk_O panelProduk_O) {
        this.panelProduk_O = panelProduk_O;
    }

        private void koneksi() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = koneksi.configDB();
            Statement stat = con.createStatement();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal terhubung ke database: ");
            e.printStackTrace(); // Cetak exception untuk debugging
        }
    }
    private void kosongkan() {
        nam.setText("");
        har.setText("");
        haris.setText(" Hari...");
        jams.setText(" Jam...");
    }        
    /**
     * 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        close = new javax.swing.JLabel();
        namproko = new javax.swing.JLabel();
        harko = new javax.swing.JLabel();
        datatak = new javax.swing.JLabel();
        hariangka = new javax.swing.JLabel();
        harirentang = new javax.swing.JLabel();
        jamangka = new javax.swing.JLabel();
        jamrentang = new javax.swing.JLabel();
        berhasils = new javax.swing.JLabel();
        jen = new combo_suggestion.ComboBoxSuggestion();
        jLabel11 = new javax.swing.JLabel();
        skembali = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        clears = new javax.swing.JButton();
        simpans = new javax.swing.JButton();
        jams = new javax.swing.JTextField();
        haris = new javax.swing.JTextField();
        nam = new javax.swing.JTextField();
        har = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();
        idpro = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frame/close.png"))); // NOI18N
        add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 200, -1, -1));

        namproko.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frame/16.png"))); // NOI18N
        add(namproko, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, -1, -1));

        harko.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frame/15.png"))); // NOI18N
        add(harko, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, -1, -1));

        datatak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frame/12.png"))); // NOI18N
        add(datatak, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, -1, -1));

        hariangka.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frame/6.png"))); // NOI18N
        add(hariangka, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, -1, -1));

        harirentang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frame/5.png"))); // NOI18N
        add(harirentang, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, -1, -1));

        jamangka.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frame/4.png"))); // NOI18N
        add(jamangka, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, -1, -1));

        jamrentang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frame/3.png"))); // NOI18N
        add(jamrentang, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, -1, -1));

        berhasils.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frame/Tambahkan subjudul.png"))); // NOI18N
        add(berhasils, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, -1, -1));

        jen.setBorder(null);
        jen.setEditable(false);
        jen.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Kilogram", "Satuan" }));
        add(jen, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 240, 140, 20));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frame/Frame 2 (1).png"))); // NOI18N
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 230, -1, 40));

        skembali.setBackground(new java.awt.Color(128, 147, 131));
        skembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                skembaliMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frame/Desain tanpa judul (38).png"))); // NOI18N
        skembali.add(jLabel1);

        add(skembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 530, 50, 50));

        clears.setBackground(new java.awt.Color(11, 146, 215));
        clears.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        clears.setForeground(new java.awt.Color(255, 255, 255));
        clears.setText("Clear");
        clears.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearsActionPerformed(evt);
            }
        });
        add(clears, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 480, 90, 30));

        simpans.setBackground(new java.awt.Color(10, 172, 42));
        simpans.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        simpans.setForeground(new java.awt.Color(255, 255, 255));
        simpans.setText("Simpan");
        simpans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpansActionPerformed(evt);
            }
        });
        add(simpans, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 480, -1, 30));

        jams.setBorder(null);
        jams.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jamsFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jamsFocusLost(evt);
            }
        });
        jams.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jamsActionPerformed(evt);
            }
        });
        add(jams, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 400, 80, 20));

        haris.setBorder(null);
        haris.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                harisFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                harisFocusLost(evt);
            }
        });
        haris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                harisActionPerformed(evt);
            }
        });
        add(haris, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 400, 80, 20));

        nam.setBorder(null);
        nam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namActionPerformed(evt);
            }
        });
        add(nam, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, 270, 20));

        har.setBorder(null);
        har.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                harActionPerformed(evt);
            }
        });
        add(har, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 320, 270, 20));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frame/Frame 2.png"))); // NOI18N
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 390, -1, 40));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frame/Frame 2.png"))); // NOI18N
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 390, -1, 40));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frame/Frame 1.png"))); // NOI18N
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 310, -1, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frame/Frame 1.png"))); // NOI18N
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, 400, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Batas Waktu");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 360, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Nama Produk");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Jenis Produk");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 190, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Harga Produk");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 280, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Perbarui Data");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 170, 50));

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frame/KK (17).png"))); // NOI18N
        add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        idpro.setEditable(false);
        add(idpro, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, 230, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void harisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_harisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_harisActionPerformed

    private void namActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namActionPerformed

    private void harActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_harActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_harActionPerformed

    private void jamsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jamsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jamsActionPerformed

    private void simpansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpansActionPerformed
   
    String id = idpro.getText();
    String nama = nam.getText();
    String harga = har.getText();
    String jenis = (String) jen.getSelectedItem();
    String hari = haris.getText().trim();
    String jam = jams.getText().trim();
        if (harga.isEmpty()) {
            harko.setVisible(true);
            close.setVisible(true);
            // Close the correct JLabel after 3 seconds
            Timer timerCorrect = new Timer(1000, (e) -> {
                harko.setVisible(false);
                close.setVisible(false);
            });
            timerCorrect.setRepeats(false); // Setel agar timer hanya berjalan sekali
            timerCorrect.start();
            return;
        }

        if (nama.isEmpty()) {
            namproko.setVisible(true);
            close.setVisible(true);
            // Close the correct JLabel after 3 seconds
            Timer timerCorrect = new Timer(1000, (e) -> {
                namproko.setVisible(false);
                close.setVisible(false);
            });
            timerCorrect.setRepeats(false); // Setel agar timer hanya berjalan sekali
            timerCorrect.start();
            return;
        }

 try {
    // Ensure that the value of "jam" is within the range of 0-24
    int jamValue = Integer.parseInt(jam);
    if (jamValue < 0 || jamValue > 24) {
        // Display the appropriate message and close button
        jamrentang.setVisible(true);
        close.setVisible(true);

        // Create a new Timer with an anonymous inner class for the ActionListener
        Timer timerCorrect = new Timer(2000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Hide the message and close button after 3 seconds
                jamrentang.setVisible(false);
                close.setVisible(false);
            }
        });
        timerCorrect.setRepeats(false); // Set to run only once
        timerCorrect.start(); // Start the timer
        return;
    }
} catch (NumberFormatException e) {
    // Display the appropriate message and close button
    jamangka.setVisible(true);
    close.setVisible(true);

    // Create a new Timer with an anonymous inner class for the ActionListener
    Timer timerIncorrect = new Timer(2000, new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            // Hide the message and close button after 3 seconds
            jamangka.setVisible(false);
            close.setVisible(false);
        }
    });
    timerIncorrect.setRepeats(false); // Set to run only once
    timerIncorrect.start(); // Start the timer

    return;
}

        try {
    // Ensure that the value of "jam" is within the range of 0-24
        int hariValue = Integer.parseInt(hari);
        if (hariValue < 0 || hariValue > 356) {
        // Display the appropriate message and close button
        harirentang.setVisible(true);
        close.setVisible(true);

        // Create a new Timer with an anonymous inner class for the ActionListener
        Timer timerCorrect = new Timer(2000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Hide the message and close button after 3 seconds
                harirentang.setVisible(false);
                close.setVisible(false);
            }
        });
        timerCorrect.setRepeats(false); // Set to run only once
        timerCorrect.start(); // Start the timer
        return;
    }
} catch (NumberFormatException e) {
    // Display the appropriate message and close button
    hariangka.setVisible(true);
    close.setVisible(true);

    // Create a new Timer with an anonymous inner class for the ActionListener
    Timer timerIncorrect = new Timer(2000, new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            // Hide the message and close button after 3 seconds
            hariangka.setVisible(false);
            close.setVisible(false);
        }
    });
    timerIncorrect.setRepeats(false); // Set to run only once
    timerIncorrect.start(); // Start the timer

    return;
}
    try {
        Connection conn = koneksi.configDB();
        
        // Gunakan pernyataan UPDATE untuk memperbarui data yang ada
        String sql = "UPDATE produk SET nama_produk = ?, harga_produk = ?, jenis_produk = ?, hari = ?, jam = ? WHERE id_produk=?";
        PreparedStatement p = conn.prepareStatement(sql);
        p.setString(1, nama);
        p.setString(2, harga);
        p.setString(3, jenis);
        p.setString(4, hari);
        p.setString(5, jam);
        p.setString(6, id);
        int updatedRows = p.executeUpdate();
        
        // Periksa apakah ada baris yang diperbarui
        if (updatedRows > 0) {
            // Tampilkan label berhasils
            berhasils.setVisible(true);
            close.setVisible(true);
            // Close the correct JLabel after 3 seconds
            Timer timerCorrect = new Timer(1000, (e) -> {
                berhasils.setVisible(false);
                close.setVisible(false);

                // Kembali ke halaman panelProduk_O setelah menampilkan label berhasils
                MainOwner mainInstance = (MainOwner) SwingUtilities.getWindowAncestor(this);
                mainInstance.showFormOwner(new frame.panelProduk_O(mainInstance));
            });
            timerCorrect.setRepeats(false); // Setel agar timer hanya berjalan sekali
            timerCorrect.start(); // Mulai timer

        } else {
            // Tampilkan label berhasils
            datatak.setVisible(true);
            close.setVisible(true);
            // Close the correct JLabel after 3 seconds
            Timer timerCorrect = new Timer(1000, (e) -> {
                datatak.setVisible(false);
                close.setVisible(false);
            });
            timerCorrect.setRepeats(false); // Setel agar timer hanya berjalan sekali
            timerCorrect.start(); // Mulai timer
        }

        nam.setText("");
        har.setText("");
    } catch (SQLException e) {
        System.out.println("Update Error: " + e.getMessage());
    }
    }//GEN-LAST:event_simpansActionPerformed

    private void skembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_skembaliMouseClicked
        // TODO add your handling code here:
            // Mendapatkan referensi ke objek Main dari panelForm
    MainOwner mainInstance = (MainOwner) SwingUtilities.getWindowAncestor(this);
    
    // Menampilkan kembali panelProduk_O
    mainInstance.showFormOwner(new frame.panelProduk_O(mainInstance));

    }//GEN-LAST:event_skembaliMouseClicked

    private void harisFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_harisFocusGained
        // TODO add your handling code here:
        if(haris.getText().equals(" Hari...")) {
            haris.setText("");
            haris.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_harisFocusGained

    private void harisFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_harisFocusLost
               if(haris.getText().equals("")) {
            haris.setText(" Hari...");
            haris.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_harisFocusLost

    private void jamsFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jamsFocusGained
        // TODO add your handling code here:
                        if(jams.getText().equals(" Jam...")) {
            jams.setText("");
            jams.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_jamsFocusGained

    private void jamsFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jamsFocusLost
               if(jams.getText().equals("")) {
            jams.setText(" Jam...");
            jams.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_jamsFocusLost

    private void clearsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clearsActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel berhasils;
    private javax.swing.JLabel bg;
    private javax.swing.JButton clears;
    private javax.swing.JLabel close;
    private javax.swing.JLabel datatak;
    public static javax.swing.JTextField har;
    private javax.swing.JLabel hariangka;
    private javax.swing.JLabel harirentang;
    public static javax.swing.JTextField haris;
    private javax.swing.JLabel harko;
    public static javax.swing.JTextField idpro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jamangka;
    private javax.swing.JLabel jamrentang;
    public static javax.swing.JTextField jams;
    public static combo_suggestion.ComboBoxSuggestion jen;
    public static javax.swing.JTextField nam;
    private javax.swing.JLabel namproko;
    private javax.swing.JButton simpans;
    private javax.swing.JPanel skembali;
    // End of variables declaration//GEN-END:variables
}
