/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frame;

import com.lowagie.text.Chunk;
import com.lowagie.text.Document;
import com.lowagie.text.Element;
import com.lowagie.text.FontFactory;
import com.lowagie.text.Paragraph;
import com.lowagie.text.Phrase;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import java.awt.Font;
import java.io.File;
import java.io.FileOutputStream;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.TreeMap;
import java.util.concurrent.TimeUnit;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author YAVIE
 */
public class Pilih extends javax.swing.JFrame {
private String startDate;
private String endDate;
    /**
     * Creates new form Pilih
     */
    public Pilih() {
        initComponents();
    }
    private PdfPCell createCell(String content, float fontSize, int fontStyle) {
        com.lowagie.text.Font cellFont = FontFactory.getFont(FontFactory.TIMES_ROMAN, fontSize, fontStyle);
        PdfPCell cell = new PdfPCell(new Phrase(content, cellFont));
        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
        return cell;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        date1 = new Tanggal.DateChooser();
        date2 = new Tanggal.DateChooser();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        pdf_btn = new javax.swing.JButton();
        clear_btn = new javax.swing.JButton();
        kmbali = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        dateS = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        dateP = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        sampais = new javax.swing.JTextField();
        daris = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        date1.setForeground(new java.awt.Color(153, 153, 255));
        date1.setDateFormat("yyyy-MM-dd");
        date1.setTextRefernce(daris);

        date2.setForeground(new java.awt.Color(0, 153, 153));
        date2.setDateFormat("yyyy-MM-dd");
        date2.setTextRefernce(sampais);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frame/calendar (2).png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pdf_btn.setBackground(new java.awt.Color(255, 0, 0));
        pdf_btn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pdf_btn.setForeground(new java.awt.Color(255, 255, 255));
        pdf_btn.setText("Print");
        pdf_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdf_btnActionPerformed(evt);
            }
        });
        getContentPane().add(pdf_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, -1, -1));

        clear_btn.setBackground(new java.awt.Color(0, 204, 204));
        clear_btn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        clear_btn.setForeground(new java.awt.Color(255, 255, 255));
        clear_btn.setText("Clear");
        clear_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_btnActionPerformed(evt);
            }
        });
        getContentPane().add(clear_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, -1, -1));

        kmbali.setBackground(new java.awt.Color(255, 255, 255));
        kmbali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kmbaliMouseClicked(evt);
            }
        });

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frame/Desain tanpa judul (40).png"))); // NOI18N

        javax.swing.GroupLayout kmbaliLayout = new javax.swing.GroupLayout(kmbali);
        kmbali.setLayout(kmbaliLayout);
        kmbaliLayout.setHorizontalGroup(
            kmbaliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kmbaliLayout.createSequentialGroup()
                .addComponent(jLabel16)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        kmbaliLayout.setVerticalGroup(
            kmbaliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kmbaliLayout.createSequentialGroup()
                .addComponent(jLabel16)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(kmbali, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 40, 30));

        dateS.setBackground(new java.awt.Color(255, 255, 255));
        dateS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dateSMouseClicked(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frame/calendar (2).png"))); // NOI18N

        javax.swing.GroupLayout dateSLayout = new javax.swing.GroupLayout(dateS);
        dateS.setLayout(dateSLayout);
        dateSLayout.setHorizontalGroup(
            dateSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dateSLayout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(0, 16, Short.MAX_VALUE))
        );
        dateSLayout.setVerticalGroup(
            dateSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dateSLayout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        getContentPane().add(dateS, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 40, 30));

        dateP.setBackground(new java.awt.Color(255, 255, 255));
        dateP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                datePMouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frame/calendar (2).png"))); // NOI18N

        javax.swing.GroupLayout datePLayout = new javax.swing.GroupLayout(dateP);
        dateP.setLayout(datePLayout);
        datePLayout.setHorizontalGroup(
            datePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datePLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 16, Short.MAX_VALUE))
        );
        datePLayout.setVerticalGroup(
            datePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datePLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        getContentPane().add(dateP, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 40, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel2.setText("Sampai");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel1.setText("Dari");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));
        getContentPane().add(sampais, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 180, 30));
        getContentPane().add(daris, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 180, 30));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel15.setText("Pilih Tanggal");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frame/Desain tanpa judul (43).png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getAccessibleContext().setAccessibleDescription("");

        setSize(new java.awt.Dimension(400, 300));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void datePMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datePMouseClicked
        date1.showPopup();
    }//GEN-LAST:event_datePMouseClicked

    private void dateSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dateSMouseClicked
        date2.showPopup();
    }//GEN-LAST:event_dateSMouseClicked

    private void kmbaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kmbaliMouseClicked
        dispose();
    }//GEN-LAST:event_kmbaliMouseClicked

    private void clear_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_btnActionPerformed
            sampais.setText("");
    daris.setText("");
    }//GEN-LAST:event_clear_btnActionPerformed

    private void pdf_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdf_btnActionPerformed
    // Simpan tanggal dari daris dan sampais ke variabel startDate dan endDate
    startDate = daris.getText();
    endDate = sampais.getText();

    // Validasi rentang tanggal
    if (!isDateRangeValid(startDate, endDate)) {
        JOptionPane.showMessageDialog(null, "Rentang tanggal harus antara 7 hingga 365 hari.", "Error", JOptionPane.ERROR_MESSAGE);
        return; // Keluar dari metode jika rentang tanggal tidak valid
    }

    // Mendapatkan referensi ke panelKeuangan
    panelKeuangan P_Keuangan = new panelKeuangan(); 

    // Mendapatkan data dari tabel di panelKeuangan
    JTable tabels = P_Keuangan.getTabels();

    // Mendapatkan path penyimpanan PDF dari panelKeuangan
    String path = P_Keuangan.getPathForPDF();

    // Lanjutkan proses pembuatan laporan PDF
    createPDF(tabels, path, startDate, endDate);

    }//GEN-LAST:event_pdf_btnActionPerformed
private void createPDF(JTable tabels, String path, String startDate, String endDate) {
    // Mengelompokkan data berdasarkan bulan dan tahun
    Map<String, List<Object[]>> groupedData = new TreeMap<>();
    for (int i = 0; i < tabels.getRowCount(); i++) {
        String tgl = tabels.getValueAt(i, 1).toString();
        // Cek apakah tanggal berada dalam rentang yang dipilih
        if (tgl.compareTo(startDate) >= 0 && tgl.compareTo(endDate) <= 0) {
            String bulanTahun = getMonthYearFromDate(tgl); 
            if (!groupedData.containsKey(bulanTahun)) {
                groupedData.put(bulanTahun, new ArrayList<>());
            }
            groupedData.get(bulanTahun).add(new Object[]{
                tabels.getValueAt(i, 0),
                tabels.getValueAt(i, 1),
                tabels.getValueAt(i, 2),
                tabels.getValueAt(i, 3),
                tabels.getValueAt(i, 4)
            });
        }
    }
    // Membuat dokumen PDF
    Document doc = new Document();
    try {
        // Membuat file PDF dengan nama "LaporanKeuangan.pdf"
        PdfWriter.getInstance(doc, new FileOutputStream(path + File.separator + "LaporanKeuanganPerminggu.pdf"));
        doc.open();

        // Judul
        com.lowagie.text.Font titleFont = FontFactory.getFont(FontFactory.TIMES_ROMAN, 14, Font.BOLD);
        Paragraph title = new Paragraph("Laporan Keuangan Laundry Visimala", titleFont);
        title.setAlignment(Element.ALIGN_CENTER);
        doc.add(title);
        doc.add(Chunk.NEWLINE);

        // Membuat tabel untuk setiap bulan dan tahun
        for (Map.Entry<String, List<Object[]>> entry : groupedData.entrySet()) {
            String bulanTahun = entry.getKey();
            List<Object[]> data = entry.getValue();

            // Judul bulan dan tahun
            doc.add(new Paragraph("Bulan: " + bulanTahun));
            doc.add(Chunk.NEWLINE);

            // Tabel
            PdfPTable tbl = new PdfPTable(4);
            tbl.addCell(createCell("Tanggal", 12, Font.BOLD));
            tbl.addCell(createCell("Laba", 12, Font.BOLD));
            tbl.addCell(createCell("Pemasukan", 12, Font.BOLD));
            tbl.addCell(createCell("Pengeluaran", 12, Font.BOLD));

            // Mengisi data dari tabel
            for (Object[] row : data) {
                tbl.addCell(createCell(row[0].toString(), 12, com.lowagie.text.Font.NORMAL));
                tbl.addCell(createCell(row[1].toString(), 12, com.lowagie.text.Font.NORMAL));
                tbl.addCell(createCell(row[2].toString(), 12, com.lowagie.text.Font.NORMAL));
                tbl.addCell(createCell(row[3].toString(), 12, com.lowagie.text.Font.NORMAL));
               
            }

            // Menambahkan total laba, pemasukan, dan pengeluaran di bawah tabel
            tbl.addCell(createCell("Total", 12, Font.BOLD));
            tbl.addCell(createCell("", 12, Font.BOLD));
            tbl.addCell(createCell(calculateTotal(data, 1), 12, Font.BOLD)); // Kolom laba
            tbl.addCell(createCell(calculateTotal(data, 2), 12, Font.BOLD)); // Kolom pemasukan
            tbl.addCell(createCell(calculateTotal(data, 3), 12, Font.BOLD)); // Kolom pengeluaran

            doc.add(tbl);
            doc.add(Chunk.NEWLINE);
        }
        JOptionPane.showMessageDialog(null, "PDF Generated");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Something Went Wrong: " + e.getMessage());
        e.printStackTrace();
    } finally {
        if (doc != null) {
            doc.close();
        }
    }
}
private String getMonthYearFromDate(String date) {
    SimpleDateFormat sdf = new SimpleDateFormat("MMMM yyyy", Locale.getDefault());
    Date tanggal;
    try {
        tanggal = new SimpleDateFormat("yyyy-MM-dd").parse(date);
    } catch (ParseException e) {
        tanggal = new Date(); // Default to current date if parsing fails
    }
    return sdf.format(tanggal);
}
private String calculateTotal(List<Object[]> data, int columnIndex) {
    double total = 0;
    for (Object[] row : data) {
        String value = row[columnIndex].toString().replace("Rp.", "").trim(); // Menghilangkan "Rp." dan spasi
        total += Double.parseDouble(value);
    }
    return String.valueOf(total);
}
private boolean isDateRangeValid(String startDate, String endDate) {
    // Menghitung jumlah hari antara dua tanggal
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    try {
        Date start = sdf.parse(startDate);
        Date end = sdf.parse(endDate);
        long diffInMillies = Math.abs(end.getTime() - start.getTime());
        long diff = TimeUnit.DAYS.convert(diffInMillies, TimeUnit.MILLISECONDS);
        // Validasi rentang tanggal (7 - 28 hari)
        return diff >= 7 && diff <= 365;
    } catch (ParseException e) {
        e.printStackTrace();
        return false;
    }
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pilih.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pilih.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pilih.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pilih.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pilih().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clear_btn;
    private javax.swing.JTextField daris;
    private Tanggal.DateChooser date1;
    private Tanggal.DateChooser date2;
    private javax.swing.JPanel dateP;
    private javax.swing.JPanel dateS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel kmbali;
    private javax.swing.JButton pdf_btn;
    private javax.swing.JTextField sampais;
    // End of variables declaration//GEN-END:variables
}
